= Rust programming language learning resources
:toc:

== Books (printed, ebooks)

=== The Rust Programming Language (aka _The Book_)
https://doc.rust-lang.org/book/[_The Rust Programming Language_] (online), also as printed https://nostarch.com/Rust2018[_The Rust Programming Language_]  +
Steve Klabnik and Carol Nichols, with contributions from the Rust Community +
Released: Ongoing, with each new release of the Rust +
Publisher: (printed) No Starch Press +
Code: https://github.com/rust-lang/book/
⭐⭐⭐


=== Programming Rust, 2nd Edition
https://www.oreilly.com/library/view/programming-rust-2nd/9781492052586/[_Programming Rust, 2nd Edition_] 
Jim Blandy, Jason Orendorff, Leonora F.S. Tindall +
Released: June 2021 +
Publisher: O'Reilly Media, Inc. +
Code repo: https://github.com/ProgrammingRust +
Errata: https://www.oreilly.com/catalog/errata.csp?isbn=0636920258049



== Video (full courses, tutorials, conference talks)

=== Rust in Motion
https://www.manning.com/livevideo/rust-in-motion[_Rust in Motion_], Carol Nichols, Jake Goulding +
Released: November 2019 +
Publisher: Manning Publications +
Running time: 4h 7m +
Code repo: https://github.com/integer32llc/rust-in-motion-videos 

_Publisher description_: See it. Do it. Learn it! In Rust in Motion, premier Rust experts Carol Nichols and Jake Goulding, introduce you to the Rust programming language! Designed for modern systems programming, Rust delivers impressive speed and thread-safe concurrency. As coauthor of The Rust Programming Language, Carol literally helped write “The Book,” as the Rust community affectionately calls it. Jake created the Rust FFI Omnibus, and he’s also the #1 contributor to the Rust tag on Stack Overflow. If you’re ready to get started writing production-quality lightning-fast systems code, this liveVideo course is for you! 

